#!/bin/bash

# /usr/sbin/emerge-depclean <optional package names>
# Wrapper for "emerge --depclean" wih additional safe guards as default parameters.

emerge --ask --verbose --deep --keep-going --jobs 3 --depclean "$@" || exit 1
