#!/bin/bash

# /usr/sbin/emerge-sync
# Operations depends on setup configuration:
#
#  1. _Standalone:_ For standalone installations `emerge-sync` is a wrapper
#     around `emerge --sync` with some extra flags similar to the other
#     `emerge-*` scripts.
#  2. _Build server:_ For build servers the script is a no-op.
#     A build server is running in a chroot environment, uses the same
#     repositories as the host and assumes that the host syncs the
#     repositories.
#  3. _Build client:_ For build clients the script synchronizes the Portage
#     configuration with the build server and updates package repositories.
#     The location of the upstream (build server) configuration is read
#     from `/etc/mhnnet-emerge.conf`.
#     The script for synchronizes
#     
#      - `/etc/portage`
#      - `/var/lib/portage_world`
#      - `/var/lib/portage_sets`
#     
#     with the build server to keep the configuration consistent.
#     Then the script updates the package repositories (via `emerge --sync`)
#     as usual.

source /etc/mhnnet-emerge.conf
RSYNC_OPTIONS="--whole-file --archive --human-readable --progress --one-file-system --prune-empty-dirs --quiet --delete"
SERVER_PATH_PREFIX="${SYNC_USER}@${SYNC_SERVER}:/srv/gentoo-build/${SYNC_BUILD_NAME}"

##
## Logging helpers
##

info() {
	echo -e " ${NOCOLOR-\e[1;32m*\e[0m }${*}" >&2
}

warning() {
	echo -e " ${NOCOLOR-\e[1;33m*\e[0m }${*}" >&2
}

error() {
	echo -e " ${NOCOLOR-\e[1;31m*\e[0m }${*}" >&2
}

die() {
	error ${*}
	exit 1
}

##
## Functions for each main steps of the script
## (roughly ordered as they are called in a typical program flow)
##

check_config() {
	case "${SETUP_TYPE}" in
		"standalone"|"build-server")
			;;
		"build-client")
			[[ -v SYNC_USER && -v SYNC_SERVER && -v SYNC_BUILD_NAME ]] || die "Mandatory options SYNC_USER, SYNC_SERVER or SYNC_BUILD_NAME not set for setup type \"build-client\".";;
		*)
			die "Unknown setup type";;
	esac
}

sync_portage_config() {
	info "Syncing portage configuration ..."
# For reasons which I have not fully understood, it is not possible to put the
# filter rules into a bash variable, because bash performs some strange variable
# expansion
	rsync --filter '- make.conf' \
	      --filter '- *~' \
	      --filter '- binrepos.conf/' \
	      --filter '- repos.conf/' \
	      --filter '- gnupg/' \
	      ${RSYNC_OPTIONS} ${SERVER_PATH_PREFIX}/etc/portage/               /etc/portage/     || die "Could not sync /etc/portage"
	rsync ${RSYNC_OPTIONS} ${SERVER_PATH_PREFIX}/var/lib/portage/world      /var/lib/portage/ || die "Could not sync /var/lib/portage/world"
	rsync ${RSYNC_OPTIONS} ${SERVER_PATH_PREFIX}/var/lib/portage/world_sets /var/lib/portage/ || die "Could not sync /var/lib/portage/world_sets"
}

sync_package_repositories() {
	info "Syncing package repositories ..."
	emerge --sync || die "Could not sync package repositories"
}

## Main function

main() {
	[[ -n ${NOCOLOR+yes} ]] && NOCOLOR=
	check_config
	case "${SETUP_TYPE}" in
		"standalone")
			sync_package_repositories;;
		"build-server")
			;;
		"build-client")
			sync_portage_config
			sync_package_repositories
			;;
		*)
			die "Unknown setup type";;
	esac
}

main
